services:
  chess-db:
    image: postgres:16-alpine
    container_name: chess-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSW}
      POSTGRES_DB: ${CHESS_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  chess-api:
    build:
      context: .
      dockerfile: ChessOnline.API/Dockerfile
    container_name: chess-api
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - chess-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=chess-postgres;Port=5432;Database=${CHESS_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSW}

  chess-client:
    build:
      context: .
      dockerfile: ChessOnline.Client/Dockerfile
    container_name: chess-client
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - chess-api

volumes:
  pgdata:
